build-job:
  stage: build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - echo "Running..."
    - sleep 8
    - echo "Finished!"

build-2-job:
  stage: build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - echo "Running..."
    - sleep 10
    - echo "Finished!"
